### ISSUE TITLE
Package breaks Find in Project functionality

### ISSUE THREAD

**Issue by LoneBoco** [russlescai/atom-default-encoding#1]
Find in Project is broken by this package.

```
    # No config found, try to autodetect.
    filePath = editor.getPath()
```

An exception gets thrown there as editor is undefined.  I was able to fix it locally by adding this before it:

```
    return if editor == undefined

    # No config found, try to autodetect.
    filePath = editor.getPath()
    return unless fs.existsSync(filePath)
```

**Comment by LoneBoco** [comment]
Find in Files should be "Find in Project".

**Comment by russlescai** [comment]
Sorry about the delay @LoneBoco , I have added the null check for editor, which should fix find in project. 

Thanks for raising this.
